version: 2
jobs:
  build_syscode_service:
    docker: 
      - image: circleci/node:7.10
    working_directory: /ambizphase1-main-impl-dev
    steps:
      - run:
         name: Modify Permisions
         command: |
            chown -R circleci:circleci /var/www 
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
           name: Build dummy container for common files
           command: |
              cd american.app.BE/common             
              docker build -t abz/abz-1/common:0.0.1 .
              docker-compose -v
      - run:
         name: Build SysCode Service Docker image
         command: |
            cd $CIRCLE_WORKING_DIRECTORY/american.app.BE/SysCode 
            docker build --cache-from=app -t melsayedalaa/americanbiz:$CIRCLE_SHA1 .

      - run:
          name: Save SysCode Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar melsayedalaa/americanbiz:$CIRCLE_SHA1

      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Push SysCode Service to DockerHub
          command: |
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
            docker tag melsayedalaa/americanbiz:$CIRCLE_SHA1 melsayedalaa/americanbiz:syscode
            docker push melsayedalaa/americanbiz
workflows:
  version: 2
  build_docker_images:
    jobs:
      - build_syscode_service