version: 2
jobs:
  build_common_image:
    working_directory: /ambizphase1-main-impl-dev
    docker: 
       - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
           name: Build Common container
           command: |
              cd american.app.BE/common             
              docker build -t abz/abz-1/common:0.0.1 .
      - run:
          name: Save common Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/common.tar abz/abz-1/common:0.0.1

      - save_cache:
          key: v1-common-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/common.tar
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /ambizphase1-main-impl-dev
  build_syscode_service:
    working_directory: /ambizphase1-main-impl-dev
    docker: 
       - image: docker:stable-git
    steps:      
      - setup_remote_docker
       - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-common-{{ .Branch }}-{{ epoch }}
      - restore_cache:
          keys:
            - v1-syscode-{{ .Branch }}
          paths:
            - /caches/syscode.tar
      - run:
         name: Build SysCode Service Docker image
         command: |
            cd $CIRCLE_WORKING_DIRECTORY/american.app.BE/SysCode 
            docker build --cache-from=app -t melsayedalaa/americanbiz:$CIRCLE_SHA1 .

      - run:
          name: Save SysCode Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/syscode.tar melsayedalaa/americanbiz:$CIRCLE_SHA1

      - save_cache:
          key: v1-syscode-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/syscode.tar
      - run:
          name: Push SysCode Service to DockerHub
          command: |
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
            docker tag melsayedalaa/americanbiz:$CIRCLE_SHA1 melsayedalaa/americanbiz:syscode
            docker push melsayedalaa/americanbiz
workflows:
  version: 2
  build_docker_images:
    jobs:
      - build_common_image
      - build_syscode_service:
          requires:
            - build_common_image