version: 2
jobs:
  build_syscode_service:
    machine: true
    working_directory: /ambizphase1-main-impl-dev
    steps:
      - checkout
      # - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
           name: Build dummy container for common files
           command: |
              docker-compose -v
              cd american.app.BE/common             
              docker build -t abz/abz-1/common:0.0.1 .
      - run:
         name: Build SysCode Service Docker image
         command: |
            cd $CIRCLE_WORKING_DIRECTORY/american.app.BE/SysCode 
            docker build --cache-from=app -t melsayedalaa/americanbiz:$CIRCLE_SHA1 .

      - run:
          name: Save SysCode Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar melsayedalaa/americanbiz:$CIRCLE_SHA1

      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Push SysCode Service to DockerHub
          command: |
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
            docker push melsayedalaa/americanbiz:$CIRCLE_SHA1
workflows:
  version: 2
  build_docker_images:
    jobs:
      - build_syscode_service