apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: "okc"
  name: okc
  labels:
    app: okc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: okc
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
          env:
          - name: cluster.name
            value: okc-cluster
          volumeMounts:
          - name: esdata1
            mountPath: /usr/share/elasticsearch/data  
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9300
        - name: kibana
          image: docker.elastic.co/kibana/kibana:6.2.4
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5601
        - name: account
          image: melsayedalaa/americanbiz:account
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 2222
        - name: attachment
          image: melsayedalaa/americanbiz:attachment
          imagePullPolicy: IfNotPresent        
          ports:
          - containerPort: 5000
        - name: authorization
          image: melsayedalaa/americanbiz:authorization
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 1111
        - name: messaging
          image: melsayedalaa/americanbiz:messaging
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3000
        - name: products
          image: melsayedalaa/americanbiz:products
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 7777
        - name: quotations
          image: melsayedalaa/americanbiz:quotation
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3333
        - name: syscode
          image: melsayedalaa/americanbiz:syscode
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5555
        - name: frontend
          image: melsayedalaa/americanbiz:frontend
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: myregistrykey
      volumes:
       - name: esdata1
         emptyDir: {}