apiVersion: v1
kind: Secret
metadata:
  namespace: "okc"
  name: dockerhubsecrets
type: kubernetes.io/dockerconfigjson
data:
  docker-username: bWVsc2F5ZWRhbGFh
  docker-password: UGFzc3dvcmRANA==
  docker-server: ZG9ja2VyLmlv
  docker-email : bS5lbHNheWVkLmFsYWFAZ21haWwuY29t