pipeline {
    agent {
    dockerfile {
        filename 'Dockerfile'
        dir './american.app.BE/quotations'
    }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
                sh 'svn --version'
            }
        }
    }
}